name: test
on:
  workflow_dispatch:

jobs:
  test-run:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - uses: actions/checkout@v2

      - name: Fetch Russon (Neomutt) GPG Signing Key
        run: gpg  --keyserver keyserver.ubuntu.com --recv-keys 86C2397270DD7A561263CA4E5FAF0A6EE7371805

      - name: "Install basic build env"
        run: pacman -Syu --noconfirm --noprogressbar --needed base-devel

      - name: Build neomutt
        run: makepkg -s
