name: test
on:
  workflow_dispatch:

jobs:
  test-run:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - uses: actions/checkout@v2

      - name: Fetch Russon (Neomutt) GPG Signing Key
        run: gpg --recv-keys 86C2397270DD7A561263CA4E5FAF0A6EE7371805

      - name: Build Arch Linux package
        uses: FFY00/build-arch-package@master
        with:
          PKGBUILD: $GITHUB_WORKSPACE/neomutt/PKGBUILD
          OUTDIR: $HOME/arch-packages

