name: Build & Run Neomutt
on: push

jobs:
  test-run:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup

    steps:
      - uses: actions/checkout@v2

      - name: Install basic build env
        run: pacman -Sqyu --noconfirm --noprogressbar --needed base base-devel namcap

      - name: Add build user
        run: useradd -m -G wheel builder

      - name: Grant builder permissions
        run: chown -R builder $PWD

      - name: Edit sudo
        run: 'echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/wheel'

      - name: Fetch Russon (Neomutt) GPG Signing Key
        run: runuser -u builder -- gpg  --keyserver keyserver.ubuntu.com --recv-keys 86C2397270DD7A561263CA4E5FAF0A6EE7371805

      - name: build neomutt
        run: cd neomutt && runuser -u builder -- makepkg -sfi --noconfirm --noprogressbar

      - name: Does it run?
        run: runuser -u builder -- neomutt -v
